### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by jakobjohansson** [brooman/All#1]
I was very happy when I saw this library. It is a pioneering idea in todays modern web.

Sadly, I got very disappointed to see that it does not work with composer. How am I supposed to build a functioning web app without the entire registry of packagist in my vendor?

**SCANDALOUS**

Is composer planned in an upcoming release?

**Comment by brooman** [comment]
Yes, composer support will come soon!

**Comment by brooman** [comment]
Composer now exists in v2!
